apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev-global-cluster-0
        url: https://1.2.3.4:6443
        branch: dev
        config: dev
      - cluster: prd-global-cluster-5
        url: https://2.4.6.8:6443
        branch: main
        config: prd
  template:
    metadata:
      name: '{{.cluster}}-spring-boot-api'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/korallo159/inpost-assessment-argocd.git
          targetRevision: '{{.branch}}'
          path: apps/spring-boot-api
          helm:
            valueFiles:
            - $values/values/spring-boot-api/values-{{.config}}.yaml
        - repoURL: https://github.com/korallo159/inpost-assessment-argocd.git
          targetRevision: '{{.branch}}'
          ref: values
      destination:
        server: '{{.url}}'
        namespace: spring-boot-api
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true