apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api
spec:
  selector:
    app: spring-boot-api
  ports:
  - name: api
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: logs
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: soap
    protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP