apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        branch: main
  template:
    metadata:
      name: '{{.cluster}}-spring-boot-api'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/korallo159/assessment-apps.git
          targetRevision: '{{.branch}}'
          path: apps/spring-boot-api
          helm:
            valueFiles:
            - $values/values/spring-boot-api/values-{{.branch}}.yaml

        - repoURL: https://github.com/korallo159/assessment-apps.git
          targetRevision: '{{.branch}}'
          ref: values
      destination:
        server: '{{.url}}'
        namespace: spring-boot-api
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true